authorName: NNI Example
experimentName: linger
trialConcurrency: 1
maxExecDuration: 3h # max executable time :110h
maxTrialNum: 20 # max trial num:500
trainingServicePlatform: local
searchSpacePath: search_space.json # path of search space
useAnnotation: false
tuner:
    builtinTunerName: TPE
    classArgs:
        optimize_mode: maximize # choices: maximize, minimize
    gpuIndices: "0" # specify GPUof optimizer
trial:
    command: /root/anaconda3/envs/liger/bin/python /home/ExperimentalEvaluation/lingerwj/run_group.py  --train_data_file /home/ExperimentalEvaluation/data/github_0.6_new/train # execute commands
    codeDir: .
    gpuNum: 1
logDir: ./nni_log
localConfig:
    gpuIndices: "0" # specify GPU number
    useActiveGpu: true
assessor:
    builtinAssessorName: Medianstop
    classArgs:
        optimize_mode: maximize
        start_step: 20
