authorName: NNI Example
experimentName: vuldeepecker
trialConcurrency: 1
maxExecDuration: 5h # max executable time :110h
maxTrialNum: 40 # max trial num:500
trainingServicePlatform: local
searchSpacePath: search_space.json # path of search space
useAnnotation: false
tuner:
    builtinTunerName: TPE
    classArgs:
        optimize_mode: maximize # choices: maximize, minimize
    gpuIndices: "1" # specify GPUof optimizer
trial:
    command: python vuldeepecker.py --data_path /home/ExperimentalEvaluation/data/github_0.6_new/train --mode train
    codeDir: .
    gpuNum: 0
logDir: /home/vuldeepker/log
localConfig:
    gpuIndices: "0" # specify GPU number
    useActiveGpu: true
assessor:
    builtinAssessorName: Medianstop
    classArgs:
        optimize_mode: maximize
        start_step: 20
